# 程序访问端口
server:
    port: 8090

# 注册中心地址
eureka:
    client:
        serviceUrl: 
            defaultZone: http://localhost:8080/eureka

# 应用名称
spring:
    application:
        name: service-ribbon        