# 应用端口
server:
    port: 8091

# 服务注册中心地址
eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:8080/eureka

# 开启Feign自带的Hystrix功能
feign:
    hystrix:
        enabled: true

# 服务名称
spring:
    application:
        name: service-feign